export const routeName = {
    Home: 'Home',
    Register: 'Register',
    Main: 'Main',
    Profile: 'Profile',
    ListUser: 'ListUser',
    NewProfile: 'NewProfile',
    ProfileEdit: 'ProfileEdit',
    Maps: 'Maps',
    SelectBan: 'SelectBan',
    SocialMaps: 'SocialMaps',
    LocalCalendar: 'LocalCalendar',
    LocalHistory: 'LocalHistory',
    Persons: 'Persons',
    PersonHistory: 'PersonHistory',
}