$FirebaseSDKVersion = '7.6.0'
$RNFirebaseAsStaticFramework = true

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'pedubon' do
  config = use_native_modules!
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'Firebase/Analytics'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  use_react_native!(:path => config["reactNativePath"])




  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'pedubonTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  
  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) 
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
     end
  end
end

